import {
  LayoutDashboard,
  MessageSquare,
  Bot,
  Radio,
  Database,
  FileText,
  GitBranch,
  Wrench,
  Target,
  Clock,
  Activity,
  BarChart3,
  ScrollText,
  Settings,
  FileCode,
  Plug,
  ChevronLeft,
  PanelRightClose,
  PanelRightOpen,
  X,
  PlayCircle,
  TrendingUp,
  Bell,
  Network,
  Layers,
  HeartPulse,
  BookOpen,
  Rocket,
  Wifi,
  Wand2,
  FileCheck,
} from 'lucide-react';

export const Icons = {
  dashboard: LayoutDashboard,
  chat: MessageSquare,
  agent: Bot,
  channel: Radio,
  memory: Database,
  content: FileText,
  workflow: GitBranch,
  skill: Wrench,
  model: Target,
  cron: Clock,
  diagnostic: Activity,
  session: BarChart3,
  log: ScrollText,
  setting: Settings,
  template: FileCode,
  plugin: Plug,
  run: PlayCircle,
  usage: TrendingUp,
  alerts: Bell,
  nodes: Network,
  extensions: Layers,
  system: Settings,
  health: HeartPulse,
  knowledge: BookOpen,
  install: Rocket,
  config: FileCode,
  guide: Wand2,
  gatewayMonitor: Wifi,
  approval: FileCheck,
  chevronLeft: ChevronLeft,
  panelClose: PanelRightClose,
  panelOpen: PanelRightOpen,
  close: X,
};

export type IconName = keyof typeof Icons;
