/**
 * Robots.txt 生成工具
 * 
 * 功能:
 * 1. Robots 规则定义 (User-agent, Allow, Disallow)
 * 2. Sitemap 引用
 * 3. 通配符支持 (*, $)
 * 
 * @author ACE
 * @version 1.0.0
 */

// ==================== 类型定义 ====================

export interface RobotsRule {
  userAgent: string;
  allow?: string[];
  disallow?: string[];
  crawlDelay?: number;
}

export interface RobotsConfig {
  rules: RobotsRule[];
  sitemap?: string[];
  host?: string;
}

export interface GenerateRobotsOptions {
  /** 是否添加注释 */
  addComments?: boolean;
  /** 是否验证规则 */
  validate?: boolean;
}

// ==================== 常量定义 ====================

/** 常见 User-agent 列表 */
export const COMMON_USER_AGENTS = {
  GOOGLE: 'Googlebot',
  GOOGLE_MOBILE: 'Googlebot-Mobile',
  GOOGLE_IMAGE: 'Googlebot-Image',
  BING: 'bingbot',
  BAIDU: 'Baiduspider',
  YANDEX: 'YandexBot',
  FACEBOOK: 'facebookexternalhit',
  TWITTER: 'Twitterbot',
  LINKEDIN: 'LinkedInBot',
  SLACK: 'Slackbot-LinkExpanding',
  APPLE: 'Applebot',
  DJANGO: 'DuckDuckBot',
  YAHOO: 'Yahoo! Slurp',
  ALEXA: 'ia_archiver',
  EXABOT: 'Exabot',
  BLEXBOT: 'BLEXBot',
  SEMRUSH: 'SemrushBot',
  AHERFS: 'AhrefsBot',
  MJ12: 'MJ12bot',
  DOTBOT: 'DotBot',
  ROGERBOT: 'rogerbot',
  PINTEREST: 'Pinterest',
  WHATSAPP: 'WhatsApp',
  TELEGRAM: 'TelegramBot',
  DISCORD: 'Discordbot',
  OPENAI: 'GPTBot',
  COMMONCRAWL: 'CommonCrawl',
} as const;

/** 常见允许路径 */
export const COMMON_ALLOW_PATHS = [
  '/',
  '/public',
  '/assets',
  '/static',
  '/css',
  '/js',
  '/images',
  '/img',
  '/fonts',
  '/api/public',
  '/sitemap.xml',
  '/robots.txt',
] as const;

/** 常见禁止路径 */
export const COMMON_DISALLOW_PATHS = [
  '/admin',
  '/private',
  '/secret',
  '/internal',
  '/api/private',
  '/api/internal',
  '/tmp',
  '/temp',
  '/cache',
  '/logs',
  '/.git',
  '/.svn',
  '/.env',
  '/config',
  '/backup',
  '/backups',
  '/database',
  '/db',
  '/sql',
  '/wp-admin',
  '/wp-includes',
  '/wp-content/plugins',
  '/wp-content/themes',
  '/node_modules',
  '/bower_components',
  '/vendor',
  '/dist',
  '/build',
  '/coverage',
  '/.next',
  '/.nuxt',
  '/.output',
  '/search',
  '/?s=',
  '/search?',
  '/cgi-bin',
  '/etc',
  '/var',
  '/proc',
] as const;

// ==================== 核心函数 ====================

/**
 * 验证 robots 规则是否合法
 */
export function validateRobotsRule(rule: RobotsRule): boolean {
  if (!rule.userAgent || rule.userAgent.trim() === '') {
    return false;
  }
  
  // 验证通配符语法
  const validatePattern = (pattern: string): boolean => {
    // * 可以出现在任何位置
    // $ 只能出现在末尾
    if (pattern.includes('$') && !pattern.endsWith('$')) {
      return false;
    }
    return true;
  };
  
  const paths = [...(rule.allow || []), ...(rule.disallow || [])];
  for (const path of paths) {
    if (!validatePattern(path)) {
      return false;
    }
  }
  
  // crawl-delay 必须是非负数
  if (rule.crawlDelay !== undefined && rule.crawlDelay < 0) {
    return false;
  }
  
  return true;
}

/**
 * 生成单个 User-agent 的规则块
 */
export function generateRuleBlock(rule: RobotsRule, options: GenerateRobotsOptions = {}): string {
  const lines: string[] = [];
  const { addComments = false, validate = false } = options;
  
  // 验证
  if (validate && !validateRobotsRule(rule)) {
    throw new Error(`Invalid robots rule for user-agent: ${rule.userAgent}`);
  }
  
  // 注释
  if (addComments) {
    lines.push(`# Rules for ${rule.userAgent}`);
  }
  
  // User-agent
  lines.push(`User-agent: ${rule.userAgent}`);
  
  // Allow 规则
  if (rule.allow && rule.allow.length > 0) {
    for (const path of rule.allow) {
      lines.push(`Allow: ${path}`);
    }
  }
  
  // Disallow 规则
  if (rule.disallow && rule.disallow.length > 0) {
    for (const path of rule.disallow) {
      lines.push(`Disallow: ${path}`);
    }
  }
  
  // Crawl-delay
  if (rule.crawlDelay !== undefined) {
    lines.push(`Crawl-delay: ${rule.crawlDelay}`);
  }
  
  return lines.join('\n');
}

/**
 * 生成 Sitemap 行
 */
export function generateSitemapLine(sitemapUrl: string): string {
  return `Sitemap: ${sitemapUrl}`;
}

/**
 * 生成 Host 行
 */
export function generateHostLine(host: string): string {
  return `Host: ${host}`;
}

/**
 * 生成完整的 robots.txt 内容
 */
export function generateRobotsTxt(config: RobotsConfig, options: GenerateRobotsOptions = {}): string {
  const lines: string[] = [];
  const { addComments = false, validate = false } = options;
  
  // 文件头注释
  if (addComments) {
    lines.push('# robots.txt');
    lines.push(`# Generated by ACE Robots Utils`);
    lines.push(`# Generated at: ${new Date().toISOString()}`);
    lines.push('');
  }
  
  // Host (可选)
  if (config.host) {
    lines.push(generateHostLine(config.host));
    lines.push('');
  }
  
  // 规则块
  for (const rule of config.rules) {
    lines.push(generateRuleBlock(rule, options));
    lines.push('');
  }
  
  // Sitemap
  if (config.sitemap && config.sitemap.length > 0) {
    for (const sitemapUrl of config.sitemap) {
      lines.push(generateSitemapLine(sitemapUrl));
    }
  }
  
  return lines.join('\n').trim() + '\n';
}

// ==================== 快捷构建函数 ====================

/**
 * 创建允许所有爬虫的规则
 */
export function allowAll(userAgent: string = '*'): RobotsRule {
  return {
    userAgent,
    allow: ['/'],
  };
}

/**
 * 创建禁止所有爬虫的规则
 */
export function disallowAll(userAgent: string = '*'): RobotsRule {
  return {
    userAgent,
    disallow: ['/'],
  };
}

/**
 * 创建标准网站规则 (允许公开内容，禁止管理后台等)
 */
export function createStandardWebRules(): RobotsRule[] {
  return [
    {
      userAgent: '*',
      allow: COMMON_ALLOW_PATHS as unknown as string[],
      disallow: COMMON_DISALLOW_PATHS as unknown as string[],
    },
  ];
}

/**
 * 创建搜索引擎友好规则
 */
export function createSearchEngineFriendlyRules(): RobotsRule[] {
  return [
    {
      userAgent: COMMON_USER_AGENTS.GOOGLE,
      allow: ['/'],
      disallow: ['/search?', '/?s=', '/cgi-bin/'],
    },
    {
      userAgent: COMMON_USER_AGENTS.BING,
      allow: ['/'],
      disallow: ['/search?', '/?s=', '/cgi-bin/'],
    },
    {
      userAgent: COMMON_USER_AGENTS.BAIDU,
      allow: ['/'],
      disallow: ['/search?', '/?s=', '/cgi-bin/'],
    },
    {
      userAgent: '*',
      allow: COMMON_ALLOW_PATHS as unknown as string[],
      disallow: COMMON_DISALLOW_PATHS as unknown as string[],
      crawlDelay: 1,
    },
  ];
}

/**
 * 创建 API 服务规则
 */
export function createApiServiceRules(apiPrefix: string = '/api'): RobotsRule[] {
  return [
    {
      userAgent: '*',
      allow: [`${apiPrefix}/public`, '/health', '/status'],
      disallow: [`${apiPrefix}/`, `${apiPrefix}/*`],
    },
  ];
}

/**
 * 创建爬虫限制规则 (针对特定爬虫)
 */
export function createCrawlerRestrictionRules(
  crawlerName: string,
  restrictedPaths: string[],
  crawlDelay?: number
): RobotsRule {
  return {
    userAgent: crawlerName,
    disallow: restrictedPaths,
    crawlDelay,
  };
}

// ==================== 通配符工具函数 ====================

/**
 * 将路径模式转换为 robots.txt 通配符格式
 * 
 * 支持:
 * - * 匹配任意字符
 * - $ 匹配 URL 结尾
 */
export function toRobotsPattern(path: string): string {
  // 如果已经以 $ 结尾，保持不变
  if (path.endsWith('$')) {
    return path;
  }
  
  // 如果路径以 / 结尾，添加 * 匹配子路径
  if (path.endsWith('/')) {
    return `${path}*`;
  }
  
  return path;
}

/**
 * 创建精确匹配路径 (使用 $ 锚定结尾)
 */
export function exactMatch(path: string): string {
  if (path.endsWith('$')) {
    return path;
  }
  return `${path}$`;
}

/**
 * 创建前缀匹配路径
 */
export function prefixMatch(path: string): string {
  if (path.endsWith('*')) {
    return path;
  }
  if (path.endsWith('/')) {
    return `${path}*`;
  }
  return `${path}/*`;
}

/**
 * 创建包含特定字符串的匹配模式
 */
export function containsMatch(pattern: string): string {
  return `*${pattern}*`;
}

/**
 * 创建扩展名匹配模式
 */
export function extensionMatch(extension: string): string {
  if (!extension.startsWith('.')) {
    extension = `.${extension}`;
  }
  return `*${extension}$`;
}

// ==================== 预定义规则集 ====================

/**
 * 阻止常见 SEO 爬虫工具
 */
export function blockSeoTools(): RobotsRule {
  return {
    userAgent: '*',
    disallow: [
      '*/semrush*',
      '*/ahrefs*',
      '*/majestic*',
      '*/moz*',
      containsMatch('seo'),
      containsMatch('crawler'),
    ],
  };
}

/**
 * 阻止 AI 爬虫 (GPTBot, CCBot 等)
 */
export function blockAiCrawlers(): RobotsRule {
  return {
    userAgent: '*',
    disallow: [
      '*/gptbot*',
      '*/ccbot*',
      '*/google-extended*',
      '*/anthropic-ai*',
      '*/facebookbot*',
      '*/diffbot*',
    ],
  };
}

/**
 * 阻止常见扫描器
 */
export function blockScanners(): RobotsRule {
  return {
    userAgent: '*',
    disallow: [
      '*/scanner*',
      '*/probe*',
      '*/scan*',
      containsMatch('nikto'),
      containsMatch('nmap'),
      containsMatch('sqlmap'),
    ],
  };
}

/**
 * 阻止广告爬虫
 */
export function blockAdBots(): RobotsRule {
  return {
    userAgent: '*',
    disallow: [
      '*/adbot*',
      '*/adsbot*',
      '*/adstxt*',
      containsMatch('adcrawler'),
    ],
  };
}

// ==================== 实用工具 ====================

/**
 * 解析 robots.txt 内容
 */
export function parseRobotsTxt(content: string): RobotsConfig {
  const config: RobotsConfig = {
    rules: [],
    sitemap: [],
  };
  
  const lines = content.split('\n').map(line => line.trim());
  let currentRule: RobotsRule | null = null;
  
  for (const line of lines) {
    // 跳过空行和注释
    if (!line || line.startsWith('#')) {
      continue;
    }
    
    const [key, ...valueParts] = line.split(':');
    const keyLower = key.trim().toLowerCase();
    const value = valueParts.join(':').trim();
    
    switch (keyLower) {
      case 'user-agent':
        if (currentRule) {
          config.rules.push(currentRule);
        }
        currentRule = {
          userAgent: value,
          allow: [],
          disallow: [],
        };
        break;
        
      case 'allow':
        if (currentRule) {
          currentRule.allow?.push(value);
        }
        break;
        
      case 'disallow':
        if (currentRule) {
          currentRule.disallow?.push(value);
        }
        break;
        
      case 'crawl-delay':
        if (currentRule) {
          currentRule.crawlDelay = parseInt(value, 10);
        }
        break;
        
      case 'sitemap':
        config.sitemap?.push(value);
        break;
        
      case 'host':
        config.host = value;
        break;
    }
  }
  
  // 添加最后一个规则
  if (currentRule) {
    config.rules.push(currentRule);
  }
  
  return config;
}

/**
 * 合并多个 robots 配置
 */
export function mergeRobotsConfigs(...configs: RobotsConfig[]): RobotsConfig {
  const merged: RobotsConfig = {
    rules: [],
    sitemap: [],
  };
  
  for (const config of configs) {
    merged.rules.push(...config.rules);
    if (config.sitemap) {
      merged.sitemap.push(...config.sitemap);
    }
    if (config.host && !merged.host) {
      merged.host = config.host;
    }
  }
  
  return merged;
}

/**
 * 从配置生成下载链接
 */
export function getDataUri(config: RobotsConfig, options?: GenerateRobotsOptions): string {
  const content = generateRobotsTxt(config, options);
  const encoded = encodeURIComponent(content);
  return `data:text/plain;charset=utf-8,${encoded}`;
}

// ==================== 使用示例 ====================

/**
 * 使用示例代码
 * 
 * @example
 * ```typescript
 * import { 
 *   generateRobotsTxt, 
 *   createStandardWebRules,
 *   COMMON_USER_AGENTS,
 *   blockAiCrawlers
 * } from './robots-utils-skill';
 * 
 * // 示例 1: 标准网站配置
 * const standardConfig = {
 *   rules: createStandardWebRules(),
 *   sitemap: ['https://example.com/sitemap.xml'],
 *   host: 'https://example.com',
 * };
 * console.log(generateRobotsTxt(standardConfig, { addComments: true }));
 * 
 * // 示例 2: 阻止 AI 爬虫
 * const aiSafeConfig = {
 *   rules: [
 *     ...createStandardWebRules(),
 *     blockAiCrawlers(),
 *   ],
 *   sitemap: ['https://example.com/sitemap.xml'],
 * };
 * console.log(generateRobotsTxt(aiSafeConfig));
 * 
 * // 示例 3: 自定义规则
 * const customConfig = {
 *   rules: [
 *     {
 *       userAgent: COMMON_USER_AGENTS.GOOGLE,
 *       allow: ['/', '/public/*'],
 *       disallow: ['/admin/', '/private/$'],
 *     },
 *     {
 *       userAgent: '*',
 *       disallow: ['/'],
 *       crawlDelay: 5,
 *     },
 *   ],
 *   sitemap: [
 *     'https://example.com/sitemap.xml',
 *     'https://example.com/sitemap-news.xml',
 *   ],
 * };
 * console.log(generateRobotsTxt(customConfig, { addComments: true, validate: true }));
 * 
 * // 示例 4: 通配符使用
 * import { 
 *   exactMatch, 
 *   prefixMatch, 
 *   containsMatch, 
 *   extensionMatch 
 * } from './robots-utils-skill';
 * 
 * const wildcardConfig = {
 *   rules: [
 *     {
 *       userAgent: '*',
 *       disallow: [
 *         exactMatch('/login'),           // 精确匹配 /login
 *         prefixMatch('/api'),            // 匹配 /api/*
 *         containsMatch('temp'),          // 匹配包含 temp 的路径
 *         extensionMatch('pdf'),          // 匹配 *.pdf
 *       ],
 *     },
 *   ],
 * };
 * console.log(generateRobotsTxt(wildcardConfig));
 * ```
 */
export const EXAMPLES = {
  standard: `# 标准网站配置
const config = {
  rules: createStandardWebRules(),
  sitemap: ['https://example.com/sitemap.xml'],
  host: 'https://example.com',
};`,

  blockAi: `# 阻止 AI 爬虫
const config = {
  rules: [
    ...createStandardWebRules(),
    blockAiCrawlers(),
  ],
  sitemap: ['https://example.com/sitemap.xml'],
};`,

  custom: `# 自定义规则
const config = {
  rules: [
    {
      userAgent: 'Googlebot',
      allow: ['/', '/public/*'],
      disallow: ['/admin/', '/private/$'],
    },
    {
      userAgent: '*',
      disallow: ['/'],
      crawlDelay: 5,
    },
  ],
  sitemap: ['https://example.com/sitemap.xml'],
};`,

  wildcards: `# 通配符使用
const config = {
  rules: [
    {
      userAgent: '*',
      disallow: [
        exactMatch('/login'),      // 精确匹配
        prefixMatch('/api'),       // 前缀匹配
        containsMatch('temp'),     // 包含匹配
        extensionMatch('pdf'),     // 扩展名匹配
      ],
    },
  ],
};`,
};

export default {
  generateRobotsTxt,
  generateRuleBlock,
  generateSitemapLine,
  generateHostLine,
  validateRobotsRule,
  allowAll,
  disallowAll,
  createStandardWebRules,
  createSearchEngineFriendlyRules,
  createApiServiceRules,
  createCrawlerRestrictionRules,
  toRobotsPattern,
  exactMatch,
  prefixMatch,
  containsMatch,
  extensionMatch,
  blockSeoTools,
  blockAiCrawlers,
  blockScanners,
  blockAdBots,
  parseRobotsTxt,
  mergeRobotsConfigs,
  getDataUri,
  COMMON_USER_AGENTS,
  COMMON_ALLOW_PATHS,
  COMMON_DISALLOW_PATHS,
  EXAMPLES,
};
